version: "3.9"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_is_ready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    depends_on:
      - db
    image: rick-and-morty
    build: .
    ports:
      - ${SPRING_LOCAL_PORT}:$SPRING_DOCKER_PORT
      - ${DEBUG_PORT}:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://host.docker.internal:5432/$POSTGRES_DB?cloudSqlInstance=second-caster-375722:europe-central2:rick-and-morty-app&user=$POSTGRES_USER&password=$POSTGRES_PASSWORD",
        "spring.jpa.database-platform" : "org.hibernate.dialect.PostgreSQL10Dialect",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOLS_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"